name: Bug Report
description: Raising a bug/issue with the plugin
title: "[Bug]: "
labels: ["bug"]

body:
    - type: markdown
      attributes:
        value: |
          **Before** reporting an issue, make sure to read the [documentation](https://codecompanion.olimorris.dev) and search [existing issues](https://github.com/olimorris/codecompanion.nvim/issues).

          Usage questions such as ***"How do I...?"*** belong in [Discussions](https://github.com/olimorris/codecompanion.nvim/discussions) and will be closed.

          Finally, if you don't supply a valid `init.lua` file at the bottom of this page, your issue will be closed.

    - type: checkboxes
      attributes:
        label: Did you check the docs and existing issues?
        description: Make sure you checked all of the below before submitting an issue
        options:
          - label: I have read all the docs
            required: true
          - label: I have updated the plugin to the latest version before submitting this issue
            required: true
          - label: I have searched for existing issues/discussions
            required: true
          - label: I have searched the existing issues of plugins related to this issue
            required: true

    - type: input
      attributes:
        label: "Neovim version (nvim -v)"
        placeholder: "0.8.0 commit db1b0ee3b30f"
      validations:
        required: true
    - type: input
      attributes:
        label: "Operating system/version"
        placeholder: "MacOS 11.5"
      validations:
        required: true
    - type: input
      attributes:
        label: "Adapter and model"
        placeholder: "Copilot and GPT-4.1"
      validations:
        required: true


    - type: textarea
      attributes:
        label: Describe the bug
        description: A clear and concise description of what the bug is. Please include any related errors you see in Neovim.
      validations:
        required: true
    - type: textarea
      attributes:
        label: Steps To Reproduce
        description: Steps to reproduce the behavior.
        placeholder: |
          1.
          2.
          3.
      validations:
        required: true
    - type: textarea
      attributes:
        label: Expected Behavior
        description: A concise description of what you expected to happen.
      validations:
        required: true

    - type: markdown
      attributes:
        value: |
          ## Reproduce

          Please provide the necessary config so I can recreate this issue. It's a big ask of my time as a single maintainer to investigate all possible issues that a user is experiencing.

          Use the template `init.lua` file provided to you below. A minimal config will be created for you in your working directory under `.repro`.

    - type: textarea
      attributes:
        label: init.lua file
        description: Minimal file to reproduce this issue. Save as `init.lua` and run with `nvim -u init.lua`
        value: |
          --[[
          NOTE: Set the config path to enable the copilot adapter to work.
          It will search the following paths for a token:
            - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
            - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
          --]]
          vim.env["CODECOMPANION_TOKEN_PATH"] = vim.fn.expand("~/.config")

          vim.env.LAZY_STDPATH = ".repro"
          load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

          -- Your CodeCompanion setup
          local plugins = {
            {
              "olimorris/codecompanion.nvim",
              dependencies = {
                { "nvim-treesitter/nvim-treesitter", branch = "main", lazy = false, build = ":TSUpdate" },
                { "nvim-lua/plenary.nvim" },
                -- Test with blink.cmp (delete if not required)
                {
                  "saghen/blink.cmp",
                  lazy = false,
                  version = "*",
                  opts = {
                    keymap = {
                      preset = "enter",
                      ["<S-Tab>"] = { "select_prev", "fallback" },
                      ["<Tab>"] = { "select_next", "fallback" },
                    },
                    cmdline = { sources = { "cmdline" } },
                    sources = {
                      default = { "lsp", "path", "buffer", "codecompanion" },
                    },
                  },
                },
                -- Test with nvim-cmp
                -- { "hrsh7th/nvim-cmp" },
              },
              opts = {
                --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
                strategies = {
                  --NOTE: Change the adapter as required
                  chat = { adapter = "copilot" },
                  inline = { adapter = "copilot" },
                },
                opts = {
                  log_level = "DEBUG",
                },
              },
            },
          }

          -- Leaving this comment in to see if the issue author notices ;-)
          -- This is so I can tell if they've really tested with their own repro.lua file

          require("lazy.minit").repro({ spec = plugins })

          -- Setup Tree-sitter
          require("nvim-treesitter").install({
            "lua",
            "markdown",
            "markdown_inline",
            "yaml",
          })

          -- Setup nvim-cmp
          -- local cmp_status, cmp = pcall(require, "cmp")
          -- if cmp_status then
          --   cmp.setup({
          --     mapping = cmp.mapping.preset.insert({
          --       ["<C-b>"] = cmp.mapping.scroll_docs(-4),
          --       ["<C-f>"] = cmp.mapping.scroll_docs(4),
          --       ["<C-Space>"] = cmp.mapping.complete(),
          --       ["<C-e>"] = cmp.mapping.abort(),
          --       ["<CR>"] = cmp.mapping.confirm({ select = true }),
          --       -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
          --     }),
          --   })
          -- end
        render: lua
      validations:
        required: true

    - type: textarea
      attributes:
        label: Log output
        description: Share the output from the log file in your current working directory at `.repro/state/nvim/codecompanion.log`
      validations:
        required: false

    - type: checkboxes
      attributes:
        label: Have you provided and tested with a repro.lua file?
        description: I'll close this issue with no reason if I can't recreate it
        options:
          - label: Yes, I have tested and provided a repro.lua file
            required: true

