name: Bug Report
description: Raise an issue for something that is stopping CodeCompanion from working as expected
title: "[Bug]: "
labels: ["bug"]

body:
    - type: markdown
      attributes:
        value: |
          **Before** reporting an issue, make sure to read the [documentation](https://codecompanion.olimorris.dev) and search [existing issues](https://github.com/olimorris/codecompanion.nvim/issues)

          **What is a bug?**
          - A bug is a reproducible error that causes CodeCompanion to behave incorrectly, crash, or not work as documented
          - Minor cosmetic issues (such as extra line breaks or formatting quirks) are not considered bugs unless they impact usability or readability. Please PR any of these changes yourself
          - Feature requests, usage questions, or configuration help should go to [Discussions](https://github.com/olimorris/codecompanion.nvim/discussions)

          > [!IMPORTANT]
          > If you don't supply a valid `minimal.lua` your issue will be closed

    - type: checkboxes
      attributes:
        label: Pre-submission checklist
        description: Please confirm all of the following before submitting
        options:
          - label: I have read the [documentation](https://codecompanion.olimorris.dev)
            required: true
          - label: I have updated the plugin and all dependencies to the latest versions
            required: true
          - label: I have searched for existing [issues](https://github.com/olimorris/codecompanion.nvim/issues) and [discussions](https://github.com/olimorris/codecompanion.nvim/discussions)
            required: true
          - label: My issue is not a minor or cosmetic quirk (e.g., formatting, spacing, or other non-functional details)
            required: true

    - type: input
      attributes:
        label: "Neovim version (nvim -v)"
        placeholder: "0.8.0 commit db1b0ee3b30f"
      validations:
        required: true

    - type: input
      attributes:
        label: "Operating system/version"
        placeholder: "macOS 14.4, Ubuntu 22.04, Windows 11"
      validations:
        required: true

    - type: input
      attributes:
        label: "Adapter and model"
        placeholder: "Copilot and GPT-4.1"
      validations:
        required: true

    - type: textarea
      attributes:
        label: Describe the bug
        description: |
          A clear and concise description of the problem
          Include any error messages or unexpected behavior you observe
        placeholder: |
          When I do X ...
          I observe Y ...
          But I expect Z ...
      validations:
        required: true

    - type: textarea
      attributes:
        label: Steps to reproduce
        description: |
          List the steps to reproduce the issue
          Be as minimal and precise as possible
        placeholder: |
          1. Open Neovim with the provided minimal.lua
          2. ...
          3. ...
      validations:
        required: true

    - type: textarea
      attributes:
        label: Expected behavior
        description: What do you expect to happen?
        placeholder: |
          I expected ...
      validations:
        required: true

    - type: textarea
      attributes:
        label: Screenshots or recordings (optional)
        description: If applicable, add screenshots or a screen recording to help explain your problem
      validations:
        required: false

    - type: markdown
      attributes:
        value: |
          ## Reproduce the issue

          - Please provide a `minimal.lua` file that reproduces the issue
          - I'm a solo maintainer, so making my life easy means a lot
          - Preferably use the one [here](https://github.com/olimorris/codecompanion.nvim/blob/main/minimal.lua)
          - Save it as `minimal.lua` and run with `nvim -u minimal.lua`
          - All files will be downloaded to a `.repro` folder in your current working directory

    - type: textarea
      attributes:
        label: minimal.lua file
        render: lua
      validations:
        required: true

    - type: textarea
      attributes:
        label: Log output (optional)
        description: |
          Share the output from `.repro/state/nvim/codecompanion.log` if available
          Please redact any sensitive information
      validations:
        required: false

    - type: checkboxes
      attributes:
        label: Minimal reproduction confirmation
        description: I have provided and tested with a `minimal.lua` file as described above
        options:
          - label: Yes, I have tested and provided a `minimal.lua` file that reproduces the issue
            required: true
