blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/olimorris/codecompanion.nvim/discussions/new?category=q-a
    about: Help with your config? UI quirks? Or, you just can't get something to work the way you expect, open a question in our discussion forums.
  - name: Feature Request
    url: https://github.com/olimorris/codecompanion.nvim/discussions/new?category=ideas
    about: Suggest any ideas you have using our discussion forums.
