-- ~180-line Lua module. The model must read the file first, then make a targeted
-- edit buried in the middle of the file. Tests that context emission works at scale.

local CONTENT = {
  "local log = require('codecompanion.utils.log')",
  "",
  "---@class EventEmitter",
  "---@field _listeners table<string, function[]>",
  "---@field _max_listeners integer",
  "local EventEmitter = {}",
  "EventEmitter.__index = EventEmitter",
  "",
  "local DEFAULT_MAX_LISTENERS = 10",
  "",
  "---@return EventEmitter",
  "function EventEmitter.new()",
  "  return setmetatable({",
  "    _listeners = {},",
  "    _max_listeners = DEFAULT_MAX_LISTENERS,",
  "  }, EventEmitter)",
  "end",
  "",
  "---@param event string",
  "---@param listener function",
  "---@return EventEmitter",
  "function EventEmitter:on(event, listener)",
  "  if not self._listeners[event] then",
  "    self._listeners[event] = {}",
  "  end",
  "  local count = #self._listeners[event]",
  "  if count >= self._max_listeners then",
  "    log:warn('EventEmitter: possible memory leak, %d listeners for %q', count, event)",
  "  end",
  "  table.insert(self._listeners[event], listener)",
  "  return self",
  "end",
  "",
  "---@param event string",
  "---@param listener function",
  "---@return EventEmitter",
  "function EventEmitter:once(event, listener)",
  "  local function wrapper(...)",
  "    self:off(event, wrapper)",
  "    listener(...)",
  "  end",
  "  return self:on(event, wrapper)",
  "end",
  "",
  "---@param event string",
  "---@param listener function",
  "---@return EventEmitter",
  "function EventEmitter:off(event, listener)",
  "  if not self._listeners[event] then",
  "    return self",
  "  end",
  "  for i, l in ipairs(self._listeners[event]) do",
  "    if l == listener then",
  "      table.remove(self._listeners[event], i)",
  "      return self",
  "    end",
  "  end",
  "  return self",
  "end",
  "",
  "---@param event string",
  "---@param ... any",
  "---@return integer",
  "function EventEmitter:emit(event, ...)",
  "  if not self._listeners[event] then",
  "    return 0",
  "  end",
  "  local called = 0",
  "  for _, listener in ipairs(vim.list_slice(self._listeners[event])) do",
  "    local ok, err = pcall(listener, ...)",
  "    if not ok then",
  "      log:error('EventEmitter: listener error on %q: %s', event, err)",
  "    else",
  "      called = called + 1",
  "    end",
  "  end",
  "  return called",
  "end",
  "",
  "---@param event string",
  "---@return integer",
  "function EventEmitter:listener_count(event)",
  "  if not self._listeners[event] then",
  "    return 0",
  "  end",
  "  return #self._listeners[event]",
  "end",
  "",
  "---@param max integer",
  "function EventEmitter:set_max_listeners(max)",
  "  self._max_listeners = max",
  "end",
  "",
  "---@return string[]",
  "function EventEmitter:event_names()",
  "  local names = {}",
  "  for event, listeners in pairs(self._listeners) do",
  "    if #listeners > 0 then",
  "      table.insert(names, event)",
  "    end",
  "  end",
  "  table.sort(names)",
  "  return names",
  "end",
  "",
  "---@param event? string",
  "function EventEmitter:remove_all_listeners(event)",
  "  if event then",
  "    self._listeners[event] = {}",
  "  else",
  "    self._listeners = {}",
  "  end",
  "end",
  "",
  "---@class StateMachine : EventEmitter",
  "---@field _guards table<string, function>",
  "---@field _state string",
  "---@field _transitions table<string, table<string, string>>",
  "local StateMachine = setmetatable({}, { __index = EventEmitter })",
  "StateMachine.__index = StateMachine",
  "",
  "---@param initial string",
  "---@param transitions table<string, table<string, string>>",
  "---@return StateMachine",
  "function StateMachine.new(initial, transitions)",
  "  local self = EventEmitter.new()",
  "  self._guards = {}",
  "  self._state = initial",
  "  self._transitions = transitions or {}",
  "  return setmetatable(self, StateMachine)",
  "end",
  "",
  "---@return string",
  "function StateMachine:state()",
  "  return self._state",
  "end",
  "",
  "---@param event string",
  "---@param guard function",
  "function StateMachine:add_guard(event, guard)",
  "  self._guards[event] = guard",
  "end",
  "",
  "---@param event string",
  "---@param ... any",
  "---@return boolean, string?",
  "function StateMachine:transition(event, ...)",
  "  local available = self._transitions[self._state]",
  "  if not available then",
  "    return false, string.format('no transitions from state %q', self._state)",
  "  end",
  "  local next_state = available[event]",
  "  if not next_state then",
  "    return false, string.format('event %q not valid in state %q', event, self._state)",
  "  end",
  "  if self._guards[event] then",
  "    local allowed, reason = self._guards[event](self._state, next_state, ...)",
  "    if not allowed then",
  "      return false, reason or 'guard rejected transition'",
  "    end",
  "  end",
  "  local prev_state = self._state",
  "  self._state = next_state",
  "  self:emit('transition', prev_state, next_state, event)",
  "  self:emit(event, prev_state, next_state)",
  "  return true",
  "end",
  "",
  "---@param event string",
  "---@return boolean",
  "function StateMachine:can(event)",
  "  local available = self._transitions[self._state]",
  "  return available ~= nil and available[event] ~= nil",
  "end",
  "",
  "---@return string[]",
  "function StateMachine:available_events()",
  "  local available = self._transitions[self._state] or {}",
  "  local events = {}",
  "  for event in pairs(available) do",
  "    table.insert(events, event)",
  "  end",
  "  table.sort(events)",
  "  return events",
  "end",
  "",
  "return {",
  "  EventEmitter = EventEmitter,",
  "  StateMachine = StateMachine,",
  "}",
}

local EXPECTED = {
  "local log = require('codecompanion.utils.log')",
  "",
  "---@class EventEmitter",
  "---@field _listeners table<string, function[]>",
  "---@field _max_listeners integer",
  "local EventEmitter = {}",
  "EventEmitter.__index = EventEmitter",
  "",
  "local DEFAULT_MAX_LISTENERS = 20",
  "",
  "---@return EventEmitter",
  "function EventEmitter.new()",
  "  return setmetatable({",
  "    _listeners = {},",
  "    _max_listeners = DEFAULT_MAX_LISTENERS,",
  "  }, EventEmitter)",
  "end",
  "",
  "---@param event string",
  "---@param listener function",
  "---@return EventEmitter",
  "function EventEmitter:on(event, listener)",
  "  if not self._listeners[event] then",
  "    self._listeners[event] = {}",
  "  end",
  "  local count = #self._listeners[event]",
  "  if count >= self._max_listeners then",
  "    log:warn('EventEmitter: possible memory leak, %d listeners for %q', count, event)",
  "  end",
  "  table.insert(self._listeners[event], listener)",
  "  return self",
  "end",
  "",
  "---@param event string",
  "---@param listener function",
  "---@return EventEmitter",
  "function EventEmitter:once(event, listener)",
  "  local function wrapper(...)",
  "    self:off(event, wrapper)",
  "    listener(...)",
  "  end",
  "  return self:on(event, wrapper)",
  "end",
  "",
  "---@param event string",
  "---@param listener function",
  "---@return EventEmitter",
  "function EventEmitter:off(event, listener)",
  "  if not self._listeners[event] then",
  "    return self",
  "  end",
  "  for i, l in ipairs(self._listeners[event]) do",
  "    if l == listener then",
  "      table.remove(self._listeners[event], i)",
  "      return self",
  "    end",
  "  end",
  "  return self",
  "end",
  "",
  "---@param event string",
  "---@param ... any",
  "---@return integer",
  "function EventEmitter:emit(event, ...)",
  "  if not self._listeners[event] then",
  "    return 0",
  "  end",
  "  local called = 0",
  "  for _, listener in ipairs(vim.list_slice(self._listeners[event])) do",
  "    local ok, err = pcall(listener, ...)",
  "    if not ok then",
  "      log:error('EventEmitter: listener error on %q: %s', event, err)",
  "    else",
  "      called = called + 1",
  "    end",
  "  end",
  "  return called",
  "end",
  "",
  "---@param event string",
  "---@return integer",
  "function EventEmitter:listener_count(event)",
  "  if not self._listeners[event] then",
  "    return 0",
  "  end",
  "  return #self._listeners[event]",
  "end",
  "",
  "---@param max integer",
  "function EventEmitter:set_max_listeners(max)",
  "  self._max_listeners = max",
  "end",
  "",
  "---@return string[]",
  "function EventEmitter:event_names()",
  "  local names = {}",
  "  for event, listeners in pairs(self._listeners) do",
  "    if #listeners > 0 then",
  "      table.insert(names, event)",
  "    end",
  "  end",
  "  table.sort(names)",
  "  return names",
  "end",
  "",
  "---@param event? string",
  "function EventEmitter:remove_all_listeners(event)",
  "  if event then",
  "    self._listeners[event] = {}",
  "  else",
  "    self._listeners = {}",
  "  end",
  "end",
  "",
  "---@class StateMachine : EventEmitter",
  "---@field _guards table<string, function>",
  "---@field _state string",
  "---@field _transitions table<string, table<string, string>>",
  "local StateMachine = setmetatable({}, { __index = EventEmitter })",
  "StateMachine.__index = StateMachine",
  "",
  "---@param initial string",
  "---@param transitions table<string, table<string, string>>",
  "---@return StateMachine",
  "function StateMachine.new(initial, transitions)",
  "  local self = EventEmitter.new()",
  "  self._guards = {}",
  "  self._state = initial",
  "  self._transitions = transitions or {}",
  "  return setmetatable(self, StateMachine)",
  "end",
  "",
  "---@return string",
  "function StateMachine:state()",
  "  return self._state",
  "end",
  "",
  "---@param event string",
  "---@param guard function",
  "function StateMachine:add_guard(event, guard)",
  "  self._guards[event] = guard",
  "end",
  "",
  "---@param event string",
  "---@param ... any",
  "---@return boolean, string?",
  "function StateMachine:transition(event, ...)",
  "  local available = self._transitions[self._state]",
  "  if not available then",
  "    return false, string.format('no transitions from state %q', self._state)",
  "  end",
  "  local next_state = available[event]",
  "  if not next_state then",
  "    return false, string.format('event %q not valid in state %q', event, self._state)",
  "  end",
  "  if self._guards[event] then",
  "    local allowed, reason = self._guards[event](self._state, next_state, ...)",
  "    if not allowed then",
  "      return false, reason or 'guard rejected transition'",
  "    end",
  "  end",
  "  local prev_state = self._state",
  "  self._state = next_state",
  "  self:emit('transition', prev_state, next_state, event)",
  "  self:emit(event, prev_state, next_state)",
  "  return true",
  "end",
  "",
  "---@param event string",
  "---@return boolean",
  "function StateMachine:can(event)",
  "  local available = self._transitions[self._state]",
  "  return available ~= nil and available[event] ~= nil",
  "end",
  "",
  "---@return string[]",
  "function StateMachine:available_events()",
  "  local available = self._transitions[self._state] or {}",
  "  local events = {}",
  "  for event in pairs(available) do",
  "    table.insert(events, event)",
  "  end",
  "  table.sort(events)",
  "  return events",
  "end",
  "",
  "return {",
  "  EventEmitter = EventEmitter,",
  "  StateMachine = StateMachine,",
  "}",
}

return {
  cleanup = function(ctx)
    vim.fn.delete(ctx.test_file)
  end,

  description = "read_file + insert_edit_into_file: 180-line Lua module — model reads file, then makes a targeted edit near the top",
  name = "Large Lua module",
  tools = { "read_file", "insert_edit_into_file" },
  tools_required = { "read_file", "insert_edit_into_file" },

  setup = function()
    local test_file = vim.fn.tempname() .. ".lua"
    vim.fn.writefile(CONTENT, test_file)
    return { test_file = test_file }
  end,

  prompt = function(ctx)
    return string.format(
      [[First use @{read_file} to read `%s`, then use @{insert_edit_into_file} to change `DEFAULT_MAX_LISTENERS` from `10` to `20`.

Read the file first to confirm the exact content. Do not ask for permission — call the tools directly.]],
      ctx.test_file
    )
  end,

  validate = function(ctx, run)
    local actual = vim.fn.readfile(ctx.test_file)
    if actual[#actual] == "" then
      actual[#actual] = nil
    end
    local file_ok = vim.deep_equal(actual, EXPECTED)
    local read_called = false
    for _, call in ipairs(run.tool_calls) do
      if call.name == "read_file" then
        read_called = true
        break
      end
    end
    return file_ok and read_called,
      {
        actual = table.concat(actual, "\n"),
        expected = table.concat(EXPECTED, "\n"),
        read_called = read_called,
      }
  end,
}
