-- A realistic Python configuration loader (~120 lines).
-- Model reads the file first, then makes three targeted changes.

local CONTENT = {
  "import copy",
  "import json",
  "import os",
  "from pathlib import Path",
  "from typing import Any, Optional",
  "",
  "",
  "class ConfigError(Exception):",
  "    pass",
  "",
  "",
  "class Config:",
  '    """Application configuration with environment variable overrides."""',
  "",
  "    DEFAULTS = {",
  '        "cache": {',
  '            "backend": "memory",',
  '            "max_size": 1000,',
  '            "ttl": 300,',
  "        },",
  '        "database": {',
  '            "host": "localhost",',
  '            "name": "app",',
  '            "pool_size": 5,',
  '            "port": 5432,',
  '            "timeout": 30,',
  "        },",
  '        "debug": False,',
  '        "host": "localhost",',
  '        "log_level": "INFO",',
  '        "port": 8080,',
  "    }",
  "",
  "    def __init__(self, path: Optional[str] = None):",
  "        self._data: dict[str, Any] = {}",
  "        self._path = path",
  "        self._load_defaults()",
  "        if path:",
  "            self._load_file(path)",
  "        self._apply_env_overrides()",
  "",
  "    def _load_defaults(self) -> None:",
  "        self._data = copy.deepcopy(self.DEFAULTS)",
  "",
  "    def _load_file(self, path: str) -> None:",
  "        p = Path(path)",
  "        if not p.exists():",
  '            raise ConfigError(f"config file not found: {path}")',
  "        if not p.is_file():",
  '            raise ConfigError(f"config path is not a file: {path}")',
  "        try:",
  "            with open(p) as f:",
  "                loaded = json.load(f)",
  "        except json.JSONDecodeError as e:",
  '            raise ConfigError(f"invalid JSON in config file: {e}") from e',
  "        self._merge(self._data, loaded)",
  "",
  "    def _merge(self, base: dict, override: dict) -> None:",
  "        for key, value in override.items():",
  "            if key in base and isinstance(base[key], dict) and isinstance(value, dict):",
  "                self._merge(base[key], value)",
  "            else:",
  "                base[key] = value",
  "",
  "    def _apply_env_overrides(self) -> None:",
  "        env_map = {",
  '            "APP_DEBUG": ("debug",),',
  '            "APP_HOST": ("host",),',
  '            "APP_LOG_LEVEL": ("log_level",),',
  '            "APP_PORT": ("port",),',
  '            "DB_HOST": ("database", "host"),',
  '            "DB_NAME": ("database", "name"),',
  '            "DB_POOL_SIZE": ("database", "pool_size"),',
  '            "DB_PORT": ("database", "port"),',
  "        }",
  "        for env_var, keys in env_map.items():",
  "            value = os.getenv(env_var)",
  "            if value is None:",
  "                continue",
  "            target = self._data",
  "            for key in keys[:-1]:",
  "                target = target[key]",
  "            last_key = keys[-1]",
  "            current = target.get(last_key)",
  "            if isinstance(current, bool):",
  '                target[last_key] = value.lower() in ("1", "true", "yes")',
  "            elif isinstance(current, int):",
  "                try:",
  "                    target[last_key] = int(value)",
  "                except ValueError:",
  '                    raise ConfigError(f"env var {env_var} must be an integer, got: {value!r}")',
  "            else:",
  "                target[last_key] = value",
  "",
  "    def get(self, key: str, default: Any = None) -> Any:",
  '        keys = key.split(".")',
  "        target = self._data",
  "        for k in keys:",
  "            if not isinstance(target, dict) or k not in target:",
  "                return default",
  "            target = target[k]",
  "        return target",
  "",
  "    def require(self, key: str) -> Any:",
  "        value = self.get(key)",
  "        if value is None:",
  '            raise ConfigError(f"required config key missing: {key}")',
  "        return value",
  "",
  "    def as_dict(self) -> dict[str, Any]:",
  "        return copy.deepcopy(self._data)",
}

local EXPECTED = {
  "import copy",
  "import json",
  "import os",
  "from pathlib import Path",
  "from typing import Any, Optional",
  "",
  "",
  "class ConfigError(Exception):",
  "    pass",
  "",
  "",
  "class Config:",
  '    """Application configuration with environment variable overrides."""',
  "",
  "    DEFAULTS = {",
  '        "cache": {',
  '            "backend": "memory",',
  '            "max_size": 1000,',
  '            "ttl": 600,',
  "        },",
  '        "database": {',
  '            "host": "localhost",',
  '            "name": "app",',
  '            "pool_size": 10,',
  '            "port": 5432,',
  '            "timeout": 30,',
  "        },",
  '        "debug": False,',
  '        "host": "localhost",',
  '        "log_level": "INFO",',
  '        "port": 8080,',
  "    }",
  "",
  "    def __init__(self, path: Optional[str] = None):",
  "        self._data: dict[str, Any] = {}",
  "        self._path = path",
  "        self._load_defaults()",
  "        if path:",
  "            self._load_file(path)",
  "        self._apply_env_overrides()",
  "",
  "    def _load_defaults(self) -> None:",
  "        self._data = copy.deepcopy(self.DEFAULTS)",
  "",
  "    def _load_file(self, path: str) -> None:",
  "        p = Path(path)",
  "        if not p.exists():",
  '            raise ConfigError(f"config file not found: {path!r}")',
  "        if not p.is_file():",
  '            raise ConfigError(f"config path is not a file: {path}")',
  "        try:",
  "            with open(p) as f:",
  "                loaded = json.load(f)",
  "        except json.JSONDecodeError as e:",
  '            raise ConfigError(f"invalid JSON in config file: {e}") from e',
  "        self._merge(self._data, loaded)",
  "",
  "    def _merge(self, base: dict, override: dict) -> None:",
  "        for key, value in override.items():",
  "            if key in base and isinstance(base[key], dict) and isinstance(value, dict):",
  "                self._merge(base[key], value)",
  "            else:",
  "                base[key] = value",
  "",
  "    def _apply_env_overrides(self) -> None:",
  "        env_map = {",
  '            "APP_DEBUG": ("debug",),',
  '            "APP_HOST": ("host",),',
  '            "APP_LOG_LEVEL": ("log_level",),',
  '            "APP_PORT": ("port",),',
  '            "DB_HOST": ("database", "host"),',
  '            "DB_NAME": ("database", "name"),',
  '            "DB_POOL_SIZE": ("database", "pool_size"),',
  '            "DB_PORT": ("database", "port"),',
  "        }",
  "        for env_var, keys in env_map.items():",
  "            value = os.getenv(env_var)",
  "            if value is None:",
  "                continue",
  "            target = self._data",
  "            for key in keys[:-1]:",
  "                target = target[key]",
  "            last_key = keys[-1]",
  "            current = target.get(last_key)",
  "            if isinstance(current, bool):",
  '                target[last_key] = value.lower() in ("1", "true", "yes")',
  "            elif isinstance(current, int):",
  "                try:",
  "                    target[last_key] = int(value)",
  "                except ValueError:",
  '                    raise ConfigError(f"env var {env_var} must be an integer, got: {value!r}")',
  "            else:",
  "                target[last_key] = value",
  "",
  "    def get(self, key: str, default: Any = None) -> Any:",
  '        keys = key.split(".")',
  "        target = self._data",
  "        for k in keys:",
  "            if not isinstance(target, dict) or k not in target:",
  "                return default",
  "            target = target[k]",
  "        return target",
  "",
  "    def require(self, key: str) -> Any:",
  "        value = self.get(key)",
  "        if value is None:",
  '            raise ConfigError(f"required config key missing: {key}")',
  "        return value",
  "",
  "    def as_dict(self) -> dict[str, Any]:",
  "        return copy.deepcopy(self._data)",
}

return {
  cleanup = function(ctx)
    vim.fn.delete(ctx.test_file)
  end,

  description = "read_file + insert_edit_into_file: realistic Python config class (~110 lines) — three targeted changes after reading",
  name = "Real-world Python config",
  tools = { "read_file", "insert_edit_into_file" },
  tools_required = { "read_file", "insert_edit_into_file" },

  setup = function()
    local test_file = vim.fn.tempname() .. ".py"
    vim.fn.writefile(CONTENT, test_file)
    return { test_file = test_file }
  end,

  prompt = function(ctx)
    return string.format(
      [[First use @{read_file} to read `%s`, then use @{insert_edit_into_file} to make these three changes in a single tool call:

1. In DEFAULTS, change `"pool_size": 5` to `"pool_size": 10`
2. In DEFAULTS, change `"ttl": 300` to `"ttl": 600`
3. In `_load_file`, add `!r` to the first error message: `f"config file not found: {path}"` → `f"config file not found: {path!r}"`

Read the file first to get the exact content. Do not ask for permission — call the tools directly.]],
      ctx.test_file
    )
  end,

  validate = function(ctx, run)
    local actual = vim.fn.readfile(ctx.test_file)
    if actual[#actual] == "" then
      actual[#actual] = nil
    end
    local file_ok = vim.deep_equal(actual, EXPECTED)
    local read_called = false
    for _, call in ipairs(run.tool_calls) do
      if call.name == "read_file" then
        read_called = true
        break
      end
    end
    return file_ok and read_called,
      {
        actual = table.concat(actual, "\n"),
        expected = table.concat(EXPECTED, "\n"),
        read_called = read_called,
      }
  end,
}
