name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Release 📦
        id: release
        uses: googleapis/release-please-action@v5
        with:
          release-type: simple
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

  luarocks-upload:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ needs.release.outputs.tag_name }}
      - name: Upload to LuaRocks
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          labels: |
            neovim
